### ISSUE TITLE
Add links to headers

### ISSUE THREAD

**Issue by sasankaweera123** [ravi-aratchige/ui-ux-portfolio#1]
Add links to these: @ravi-aratchige 

[Connect with me](https://ravi-aratchige.github.io/ui-ux-portfolio/#) 
[Email me](https://ravi-aratchige.github.io/ui-ux-portfolio/#)
[Stalk me](https://ravi-aratchige.github.io/ui-ux-portfolio/#)

**Comment by ravi-aratchige** [comment]
Dear Sasanka,

Noted with thanks. Have updated the links as necessary and uploaded my resume as well. Will soon be changing my current personal site to this site.

~ Ravindu

**Comment by sasankaweera123** [comment]
Nice
